name: release

on:
  release:
    types: [created]

concurrency:
  group: publish

jobs:
  # push_to_crates:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - uses: actions/checkout@v4
  #       - uses: dtolnay/rust-toolchain@stable
  #       - uses: katyo/publish-crates@v2
  #         with:
  #             registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  package_release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
      - uses: actions/checkout@v4
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ PAT_TOKEN}}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
